#!/bin/sh
# This uses out/ and ref/ directories which I didn't check in to the repo.

python minideal.py eg/trivial >out/trivial && diff -u ref/trivial out/trivial &&
python minideal.py eg/1 >out/1 && diff -u ref/1 out/1 &&
python minideal.py eg/2 >out/2 && diff -u ref/2 out/2 &&
python minideal.py eg/library eg/3 >out/3 && diff -u ref/3 out/3 &&
python minideal.py eg/library eg/4 >out/4 && diff -u ref/4 out/4 &&
python minideal.py eg/library eg/pythagoras >out/pythagoras && diff -u ref/pythagoras out/pythagoras
